version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/prod.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80

  app:
    build:
      context: .
      dockerfile: ./docker/php/prod.Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./storage:/var/www/html/storage

  mysql:
    restart: always
    image: mysql:8.0.16
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306

volumes:
  mysqldata:
    driver: "local"
